periodics:

  - name: ci-openenclave-mbedtls-ping
    extra_refs:
    - org: openenclave
      repo: openenclave-mbedtls
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave-mbedtls/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-mbedtls-Rhel8BuildClang-8
    extra_refs:
    - org: openenclave
      repo: openenclave-mbedtls
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave-mbedtls/job/Rhel8BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-mbedtls-Ubuntu1604BuildClang-7
    extra_refs:
    - org: openenclave
      repo: openenclave-mbedtls
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave-mbedtls/job/Ubuntu1604BuildClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-mbedtls-Ubuntu1804BuildClang-7
    extra_refs:
    - org: openenclave
      repo: openenclave-mbedtls
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave-mbedtls/job/Ubuntu1804BuildClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-mbedtls-Windows2016Build
    extra_refs:
    - org: openenclave
      repo: openenclave-mbedtls
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave-mbedtls/job/Windows2016Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        

  - name: ci-openenclave-mbedtls-Windows2019Build
    extra_refs:
    - org: openenclave
      repo: openenclave-mbedtls
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave-mbedtls/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        
