pipeline {
    agent any

    stages {

        stage('Pre-build') {
            steps{
                checkout scm
                git rebase master
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}