presubmits:
  openenclave-ci/oeedger8r-cpp:
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Release-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=clang-8'        
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Release-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=clang-7'        
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Release-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=gcc'        
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Debug-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'        
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Debug-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'        
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Debug-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1604:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=gcc'        
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Release-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=clang-8'        
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Release-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=clang-7'        
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Release-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Release --compiler=gcc'        
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Debug-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'        
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Debug-c-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'        
  - name: pr-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Debug-gcc
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/ubuntu-1804:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=Debug --compiler=gcc'        

  - name: pr-openenclave-ci-oeedger8r-cpp-jenk-rhel-8.1-Release-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
          - /bin/bash
          args:
          - -c
          - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-rhel-8.1-Release-c-8"'        

  - name: pr-openenclave-ci-oeedger8r-cpp-jenk-rhel-8.1-Debug-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
          - /bin/bash
          args:
          - -c
          - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-rhel-8.1-Debug-c-8"'        

  - name: pr-openenclave-ci-oeedger8r-cpp-jenk-win-2016-Release-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
          - /bin/bash
          args:
          - -c
          - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2016-Release-c-8"'        

  - name: pr-openenclave-ci-oeedger8r-cpp-jenk-win-2016-Debug-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
          - /bin/bash
          args:
          - -c
          - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2016-Debug-c-8"'        

  - name: pr-openenclave-ci-oeedger8r-cpp-jenk-win-2019-Release-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
          - /bin/bash
          args:
          - -c
          - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2019-Release-c-8"'        

  - name: pr-openenclave-ci-oeedger8r-cpp-jenk-win-2019-Debug-c-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
          - /bin/bash
          args:
          - -c
          - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2019-Debug-c-8"'        
