periodics:
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Release-c-8
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'        
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Release-c-7
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'        
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Release-gcc
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'        
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Debug-c-8
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'        
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Debug-c-7
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'        
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Debug-gcc
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'        
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Release-c-8
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'        
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Release-c-7
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'        
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Release-gcc
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'        
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Debug-c-8
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'        
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Debug-c-7
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'        
  - name: ci-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Debug-gcc
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'        

  - name: ci-openenclave-ci-oeedger8r-cpp-jenk-rhel-8.1-Release-c-8
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-rhel-8.1-Release-c-8"'        

  - name: ci-openenclave-ci-oeedger8r-cpp-jenk-rhel-8.1-Debug-c-8
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-rhel-8.1-Debug-c-8"'        

  - name: ci-openenclave-ci-oeedger8r-cpp-jenk-win-2016-Release-c-8
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2016-Release-c-8"'        

  - name: ci-openenclave-ci-oeedger8r-cpp-jenk-win-2016-Debug-c-8
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2016-Debug-c-8"'        

  - name: ci-openenclave-ci-oeedger8r-cpp-jenk-win-2019-Release-c-8
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2019-Release-c-8"'        

  - name: ci-openenclave-ci-oeedger8r-cpp-jenk-win-2019-Debug-c-8
    extra_refs:
    - org: openenclave-ci
      repo: oeedger8r-cpp
      base_ref: master
    decorate: true
    interval: 6h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2019-Debug-c-8"'        
