postsubmits:
  openenclave-ci/oeedger8r-cpp:
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Release-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Release-c-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Release-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Debug-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Debug-c-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1604-Debug-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Release-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Release-c-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Release-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Debug-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Debug-c-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ci-oeedger8r-cpp-ubuntu-1804-Debug-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        

  - name: post-openenclave-ci-oeedger8r-cpp-jenk-rhel-8.1-Release-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-rhel-8.1-Release-c-8"'        

  - name: post-openenclave-ci-oeedger8r-cpp-jenk-rhel-8.1-Debug-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-rhel-8.1-Debug-c-8"'        

  - name: post-openenclave-ci-oeedger8r-cpp-jenk-win-2016-Release-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2016-Release-c-8"'        

  - name: post-openenclave-ci-oeedger8r-cpp-jenk-win-2016-Debug-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2016-Debug-c-8"'        

  - name: post-openenclave-ci-oeedger8r-cpp-jenk-win-2019-Release-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2019-Release-c-8"'        

  - name: post-openenclave-ci-oeedger8r-cpp-jenk-win-2019-Debug-c-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-ci-oeedger8r-cpp-win-2019-Debug-c-8"'        
