  - name: pr-${repo}-${operating_system}-${build_type_short}-${compiler_short}
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
      - image: openenclave/${operating_system}:latest
        command:
        - /bin/bash
        args:
        - -c
        - '/hack/cmake-build.sh -b=${build_type} --compiler=${compiler}'
