periodics:

  - name: ci-openenclave-template-ping
    extra_refs:
    - org: openenclave
      repo: openenclave-template
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-template/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        
