periodics:
  - name: ci-openenclave-test-infra-validate-build-image-ubuntu-1604
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/ubuntu/1604/Dockerfile --docker_tag openenclave/ubuntu-1604:latest --docker_push --docker_user $(echo $DOCKER_USER) --docker_pass $(echo $DOCKER_PASSWORD)"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-ubuntu-1804
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/ubuntu/1804/Dockerfile --docker_tag openenclave/ubuntu-1804:latest --docker_push --docker_user $(echo $DOCKER_USER) --docker_pass $(echo $DOCKER_PASSWORD)"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-rhel-8.1
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/rhel/8.1/Dockerfile --skip_testing --docker_tag openenclave/rhel-8.1:latest --docker_push --docker_user $(echo $DOCKER_USER) --docker_pass $(echo $DOCKER_PASSWORD)"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-bootstrap-did
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/bootstap/Dockerfile --skip_testing --docker_tag openenclave/test-infra-did:latest --docker_push --docker_user $(echo $DOCKER_USER) --docker_pass $(echo $DOCKER_PASSWORD)"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-centos-7.5
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/centos/7.5/Dockerfile --skip_testing --docker_tag openenclave/centos-7.5:latest --docker_push --docker_user $(echo $DOCKER_USER) --docker_pass $(echo $DOCKER_PASSWORD)"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-validate-build-image-fedora-31
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - "-c"
            - "./images/test/build.sh --docker_path images/fedora/31/Dockerfile --skip_testing --docker_tag openenclave/fedora-31:latest --docker_push --docker_user $(echo $DOCKER_USER) --docker_pass $(echo $DOCKER_PASSWORD)"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

  - name: ci-openenclave-test-infra-jenkins-ping
    extra_refs:
    - org: openenclave-ci
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job job-runner --jenkins-user $(echo $JENKINS_USER) --url $(echo $JENKINS_URL) --jenkins-password $(echo $JENKINS_TOKEN)"

presets:
- env:
  - name: JENKINS_TOKEN
    valueFrom:
      secretKeyRef:
        name: jenkins-token
        key: jenkins-token

  - name: JENKINS_USER
    value: jenkins-trigger
  
  - name: JENKINS_URL
    value: http://oe-jenk-master-test.canadacentral.cloudapp.azure.com

  - name: DOCKER_USER
    value: openenclave

  - name: DOCKER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: docker-password
        key: docker-password
