presubmits:
  openenclave/test-infra:

  - name: pr-infra-test-infra-images-Ubuntu1804Build
    branches:
    - master
    run_if_changed: "^(config/jobs/test-infra-images//*)"
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job test-infra/job/test-infra-images/job/Ubuntu1804Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-infra-test-infra-images-Windows2019Build
    branches:
    - master
    run_if_changed: "^(config/jobs/test-infra-images//*)"
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job test-infra/job/test-infra-images/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-infra-oeedger8r-cpp-Rhel8BuildClang-8
    branches:
    - master
    run_if_changed: "^(config/jobs/oeedger8r-cpp//*)"
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job test-infra/job/oeedger8r-cpp/job/Rhel8BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-infra-oeedger8r-cpp-Ubuntu1804BuildClang-8
    branches:
    - master
    run_if_changed: "^(config/jobs/oeedger8r-cpp//*)"
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job test-infra/job/oeedger8r-cpp/job/Ubuntu1804BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-infra-oeedger8r-cpp-Windows2019Build
    branches:
    - master
    run_if_changed: "^(config/jobs/oeedger8r-cpp//*)"
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job test-infra/job/oeedger8r-cpp/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-infra-openenclave-curl-Ubuntu1804BuildClang-8
    branches:
    - master
    run_if_changed: "^(config/jobs/openenclave-curl//*)"
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job test-infra/job/openenclave-curl/job/Ubuntu1804BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-infra-openenclave-mbedtls-Rhel8BuildClang-8
    branches:
    - master
    run_if_changed: "^(config/jobs/openenclave-mbedtls//*)"
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job test-infra/job/openenclave-mbedtls/job/Rhel8BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-infra-openenclave-mbedtls-Ubuntu1804BuildClang-8
    branches:
    - master
    run_if_changed: "^(config/jobs/openenclave-mbedtls//*)"
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job test-infra/job/openenclave-mbedtls/job/Ubuntu1804BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-infra-openenclave-mbedtls-Windows2019Build
    branches:
    - master
    run_if_changed: "^(config/jobs/openenclave-mbedtls//*)"
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job test-infra/job/openenclave-mbedtls/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=$PULL_NUMBER"        
