periodics:

  - name: ci-infra-test-infra-images-Ubuntu1804Build
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job test-infra-images/job/Ubuntu1804Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-test-infra-images-Windows2019Build
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job test-infra-images/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-gperftools-ping
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job gperftools/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-oeedger8r-cpp-ping
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job oeedger8r-cpp/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-oeedger8r-cpp-Rhel8BuildClang-8
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job oeedger8r-cpp/job/Rhel8BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-oeedger8r-cpp-Ubuntu1804BuildClang-8
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job oeedger8r-cpp/job/Ubuntu1804BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-oeedger8r-cpp-Windows2019Build
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job oeedger8r-cpp/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-openenclave-build-ping
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-build/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-openenclave-ci-ping
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-ci/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-openenclave-curl-ping
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-curl/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-openenclave-curl-Ubuntu1804BuildClang-8
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-curl/job/Ubuntu1804BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-openenclave-mbedtls-ping
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-mbedtls/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-openenclave-mbedtls-Rhel8BuildClang-8
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-mbedtls/job/Rhel8BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-openenclave-mbedtls-Ubuntu1804BuildClang-8
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-mbedtls/job/Ubuntu1804BuildClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-openenclave-mbedtls-Windows2019Build
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-mbedtls/job/Windows2019Build --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-openenclave-site-ping
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-site/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-openenclave-template-ping
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-template/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        

  - name: ci-infra-public-talks-ping
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job public-talks/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"        
