  - name: ci-test-infra-${repo}-${pipeline}
    extra_refs:
    - org: openenclave
      repo: test-infra
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job ${repo}/job/${pipeline} --jenkins-user \$JENKINS_USER --url \$JENKINS_URL --jenkins-password \$JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=master"