  - name: post-test-infra-${repo}-${pipeline}
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job test-infra/job/${repo}/job/${pipeline} --jenkins-user \$JENKINS_USER --url \$JENKINS_URL --jenkins-password \$JENKINS_TOKEN --parameters  PULL_NUMBER=master"