  - name: pr-test-infra-${repo}-${pipeline}
    branches:
    - master
    run_if_changed: "^(config/jobs/${repo}/*)"
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "sleep \$(( ( RANDOM % 90 )  + 1 )) && python /hack/jenkins_bootstrap.py --wait-timer 300 --job test-infra/job/${repo}/job/${pipeline} --jenkins-user \$JENKINS_USER --url \$JENKINS_URL --jenkins-password \$JENKINS_TOKEN --parameters OE_TEST_INFRA_PULL_NUMBER=\$PULL_NUMBER"