presubmits:
  openenclave/openenclave:

  - name: pr-openenclave-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Rhel8RelWithDebInfoGCC
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Rhel8RelWithDebInfoGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Rhel8DebugClang-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Rhel8DebugClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Rhel8DebugGCC
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Rhel8DebugGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Rhel8ReleaseClang-8
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Rhel8ReleaseClang-8 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Rhel8ReleaseGCC
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Rhel8ReleaseGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1604DebugClang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1604DebugClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1604ReleaseClang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1604ReleaseClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1604RelWithDebInfoClang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1604RelWithDebInfoClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1604DebugGCC
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1604DebugGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1604ReleaseGCC
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1604ReleaseGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1604RelWithDebInfoGCC
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1604RelWithDebInfoGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1804DebugClang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1804DebugClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1804ReleaseClang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1804ReleaseClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1804RelWithDebInfoClang-7
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1804RelWithDebInfoClang-7 --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1804DebugGCC
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1804DebugGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1804ReleaseGCC
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1804ReleaseGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Ubuntu1804RelWithDebInfoGCC
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Ubuntu1804RelWithDebInfoGCC --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Windows2016Release
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Windows2016Release --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Windows2016Debug
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Windows2016Debug --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Windows2019Release
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Windows2019Release --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        

  - name: pr-openenclave-Windows2019Debug
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 10
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave/job/Windows2019Debug --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        
