periodics:
  - name: ci-openenclave-intel-SGX-FLC-Linux-2
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job Pipelines/job/Agnostic-SGX-FLC-Linux --sleep 20 --jenkins-user $JENKINS_USER --url $INTEL_URL --jenkins-password $INTEL_TOKEN"
  - name: ci-openenclave-intel-SGX1-Linux-2
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job Pipelines/job/Agnostic-SGX1-Linux --sleep 20 --jenkins-user $JENKINS_USER --url $INTEL_URL --jenkins-password $INTEL_TOKEN"
