postsubmits:
  openenclave-ci/openenclave:
  - name: post-openenclave-ubuntu-1604-Release-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1604-Release-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1604-Release-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1604-RelDebInfo-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1604-RelDebInfo-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1604-RelDebInfo-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1604-Debug-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1604-Debug-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1604-Debug-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-sgx-ubuntu-1604-Release-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1604-Release-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1604-Release-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1604-RelDebInfo-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-8 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1604-RelDebInfo-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-7 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1604-RelDebInfo-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1604-Debug-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1604-Debug-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1604-Debug-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1604:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc --hardware_mode'        
  - name: post-openenclave-ubuntu-1804-Release-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1804-Release-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1804-Release-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1804-RelDebInfo-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1804-RelDebInfo-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1804-RelDebInfo-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1804-Debug-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1804-Debug-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-ubuntu-1804-Debug-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc'
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock        
  - name: post-openenclave-sgx-ubuntu-1804-Release-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-8 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1804-Release-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=clang-7 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1804-Release-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Release --compiler=gcc --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1804-RelDebInfo-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-8 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1804-RelDebInfo-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=clang-7 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1804-RelDebInfo-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=RelWithDebInfo --compiler=gcc --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1804-Debug-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-8 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1804-Debug-clang-7
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=clang-7 --hardware_mode'        
  - name: post-openenclave-sgx-ubuntu-1804-Debug-gcc
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/ubuntu-1804:latest
          command:
            - sh
            - '-c'
            - '/hack/cmake-build.sh -b=Debug --compiler=gcc --hardware_mode'        

  - name: post-openenclave-jenk-rhel-8.1-Release-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-rhel-8.1-Release-clang-8"'        

  - name: post-openenclave-jenk-rhel-8.1-RelDebInfo-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-rhel-8.1-RelDebInfo-clang-8"'        

  - name: post-openenclave-jenk-rhel-8.1-Debug-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-rhel-8.1-Debug-clang-8"'        

  - name: post-openenclave-jenk-win-2016-Release-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-win-2016-Release-clang-8"'        

  - name: post-openenclave-jenk-win-2016-RelDebInfo-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-win-2016-RelDebInfo-clang-8"'        

  - name: post-openenclave-jenk-win-2016-Debug-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-win-2016-Debug-clang-8"'        

  - name: post-openenclave-jenk-win-2019-Release-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-win-2019-Release-clang-8"'        

  - name: post-openenclave-jenk-win-2019-RelDebInfo-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-win-2019-RelDebInfo-clang-8"'        

  - name: post-openenclave-jenk-win-2019-Debug-clang-8
    branches:
    - master
    decorate: true
    spec:
      containers:
        - image: openenclave/test-infra-did:latest
          command:
            - sh
            - '-c'
            - 'echo "I am not implemented yet! Thanks for your interest in this project! openenclave-win-2019-Debug-clang-8"'        
