periodics:
  - name: ci-openenclave-intel-SGX-FLC-Linux
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "python3 /scripts/jenkins_bootstrap.py --job Pipelines/job/Agnostic-SGX-FLC-Linux --jenkins-user $JENKINS_USER --url $INTEL_URL --jenkins-password $INTEL_TOKEN"

  - name: ci-openenclave-intel-SGX1-Linux
    extra_refs:
    - org: openenclave
      repo: openenclave
      base_ref: master
    decorate: true
    interval: 60m
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.4
          command:
            - sh
            - "-c"
            - "python3 /scripts/jenkins_bootstrap.py --job Pipelines/job/Agnostic-SGX1-Linux --jenkins-user $JENKINS_USER --url $INTEL_URL --jenkins-password $INTEL_TOKEN"
