periodics:

  - name: ci-openenclave-site-ping
    extra_refs:
    - org: openenclave
      repo: openenclave-site
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:latest
          command:
            - sh
            - "-c"
            - "python /hack/jenkins_bootstrap.py --job openenclave-site/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=master"        
