presubmits:
  openenclave/openenclave-site:

  - name: pr-openenclave-site-ping
    branches:
    - master
    always_run: true
    decorate: true
    skip_report: false
    max_concurrency: 1
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.3
          command:
            - sh
            - "-c"
            - "sleep $(( ( RANDOM % 90 )  + 1 )) && python3 /scripts/jenkins_bootstrap.py --job openenclave-site/job/ping --jenkins-user $JENKINS_USER --url $JENKINS_URL --jenkins-password $JENKINS_TOKEN --parameters PULL_NUMBER=$PULL_NUMBER"        
