# Do not change build-configs, these are the 3 types of builds we build for
build-configs:
  postsubmits
  periodics
  pre-submits

# Test-infra needs to be first due to the inverse integrations, rest in any order
repos:
  test-infra
  gperftools
  oeedger8r-cpp
  openenclave
  openenclave-build
  openenclave-ci
  openenclave-curl
  openenclave-mbedtls
  openenclave-site
  openenclave-template
  public-talks

# These corrrespond to the pipelines each repo has and are stored in the <Job DSL> directory
pipelines:
  gperftools:
    ping
  oeedger8r-cpp:
    ping
    Rhel8BuildClang-8
    Rhel8BuildGCC
    Ubuntu1604BuildClang-7
    Ubuntu1604BuildGCC
    Ubuntu1804BuildClang-7
    Ubuntu1804BuildGCC
    Windows2016Build
    Windows2019Build
  openenclave:
    ping
    Rhel8RelWithDebInfoGCC
    Rhel8DebugClang-8
    Rhel8DebugGCC
    Rhel8ReleaseClang-8
    Rhel8ReleaseGCC
    Ubuntu1604DebugClang-7
    Ubuntu1604ReleaseClang-7
    Ubuntu1604RelWithDebInfoClang-7
    Ubuntu1604DebugGCC
    Ubuntu1604ReleaseGCC
    Ubuntu1604RelWithDebInfoGCC
    Ubuntu1804DebugClang-7
    Ubuntu1804ReleaseClang-7
    Ubuntu1804RelWithDebInfoClang-7
    Ubuntu1804DebugGCC
    Ubuntu1804ReleaseGCC
    Ubuntu1804RelWithDebInfoGCC
    Windows2016BuildRel
    Windows2016BuildDebug
    Windows2019BuildRel
    Windows2019BuildDebug
  openenclave-build:
    ping
  openenclave-ci:
    ping
  openenclave-curl:
    ping
    Ubuntu1604BuildClang-7
    Ubuntu1804BuildClang-7
  openenclave-mbedtls:
    ping
    Rhel8BuildClang-8
    Rhel8BuildGCC
    Ubuntu1604BuildClang-7
    Ubuntu1604BuildGCC
    Ubuntu1804BuildClang-7
    Ubuntu1804BuildGCC
    Windows2016Build
    Windows2019Build
  openenclave-site:
    ping
  openenclave-template:
    ping
  public-talks:
    ping
