# Do not change build-configs, these are the 3 types of builds we build for
build-configs:
  postsubmits
  periodics
  pre-submits

# Test-infra needs to be first due to the inverse integrations, rest in any order
repos:
  test-infra
  gperftools
  oeedger8r-cpp
  openenclave
  openenclave-build
  openenclave-ci
  openenclave-curl
  openenclave-mbedtls
  openenclave-site
  openenclave-template
  public-talks

# These corrrespond to the pipelines each repo has and are stored in the <Job DSL> directory
pipelines:
  gperftools:
    ping
  oeedger8r-cpp:
    ping
    Rhel8BuildClang-8
    Rhel8BuildGCC
    Ubuntu1604BuildClang-7
    Ubuntu1604BuildGCC
    Ubuntu1804BuildClang-7
    Ubuntu1804BuildGCC
    Windows2016Build
    Windows2019Build
  openenclave:
    ping
    HostVerifyDeb16042019
    HostVerifyDeb18042019
    HostVerifyRel16042019
    HostVerifyRel18042019
    LinuxElfDeb16042019
    LinuxElfDeb18042019
    LinuxElfRel16042019
    LinuxElfRel18042019
    Rhel8DebugClang-8
    Rhel8DebugClang-8Snmalloc
    Rhel8DebugClang-8SnmallocE2E
    Rhel8DebugGCC
    Rhel8DebugGCCSnmalloc
    Rhel8RelWithDebInfoGCC
    Rhel8RelWithDebInfoGCCSnmalloc
    Rhel8RelWithDebInfoGCCSnmallocE2E
    Rhel8ReleaseClang-8
    Rhel8ReleaseClang-8Snmalloc
    Rhel8ReleaseClang-8SnmallocE2E
    Rhel8ReleaseGCC
    Rhel8ReleaseGCCSnmalloc
    Rhel8ReleaseGCCSnmallocE2E
    Ubuntu1604DebugClang-7
    Ubuntu1604DebugClang-7Snmalloc
    Ubuntu1604DebugClang-7SnmallocE2E
    Ubuntu1604DebugGCC
    Ubuntu1604DebugGCCSnmalloc
    Ubuntu1604DebugGCCSnmallocE2E
    Ubuntu1604RelWithDebInfoClang-7
    Ubuntu1604RelWithDebInfoClang-7Snmalloc
    Ubuntu1604RelWithDebInfoClang-7SnmallocE2E
    Ubuntu1604RelWithDebInfoGCC
    Ubuntu1604RelWithDebInfoGCCSnmalloc
    Ubuntu1604RelWithDebInfoGCCSnmallocE2E
    Ubuntu1604ReleaseClang-7
    Ubuntu1604ReleaseClang-7Snmalloc
    Ubuntu1604ReleaseClang-7SnmallocE2E
    Ubuntu1604ReleaseGCC
    Ubuntu1604ReleaseGCCSnmalloc
    Ubuntu1604ReleaseGCCSnmallocE2E
    Ubuntu1804DebugClang-7
    Ubuntu1804DebugClang-7Snmalloc
    Ubuntu1804DebugClang-7SnmallocE2E
    Ubuntu1804DebugGCC
    Ubuntu1804DebugGCCSnmalloc
    Ubuntu1804RelWithDebInfoClang-7
    Ubuntu1804RelWithDebInfoClang-7Snmalloc
    Ubuntu1804RelWithDebInfoClang-7SnmallocE2E
    Ubuntu1804RelWithDebInfoGCC
    Ubuntu1804RelWithDebInfoGCCSnmalloc
    Ubuntu1804RelWithDebInfoGCCSnmallocE2E
    Ubuntu1804ReleaseClang-7
    Ubuntu1804ReleaseClang-7Snmalloc
    Ubuntu1804ReleaseClang-7SnmallocE2E
    Ubuntu1804ReleaseGCC
    Ubuntu1804ReleaseGCCSnmalloc
    Ubuntu1804ReleaseGCCSnmallocE2E
    Win2016Debug
    Win2016DebugSnmalloc
    Win2016RelSnmalloc
    Win2016Release
    Win2019Debug
    Win2019DebugSnmalloc
    Win2019RelSnmalloc
    Win2019Release
  openenclave-build:
    ping
  openenclave-ci:
    ping
  openenclave-curl:
    ping
    Ubuntu1604BuildClang-7
    Ubuntu1804BuildClang-7
  openenclave-mbedtls:
    ping
    Rhel8BuildClang-8
    Rhel8BuildGCC
    Ubuntu1604BuildClang-7
    Ubuntu1604BuildGCC
    Ubuntu1804BuildClang-7
    Ubuntu1804BuildGCC
    Windows2016Build
    Windows2019Build
  openenclave-site:
    ping
  openenclave-template:
    ping
  public-talks:
    ping
