  - name: ci-${repo}-${pipeline}
    extra_refs:
    - org: openenclave
      repo: ${repo}
      base_ref: master
    decorate: true
    interval: 12h
    spec:
      containers:
        - image: openenclave/jenkinsoperator:0.2
          command:
            - sh
            - "-c"
            - "sleep \$(( ( RANDOM % 90 )  + 1 )) && python /hack/jenkins_bootstrap.py --job ${repo}/job/${pipeline} --jenkins-user \$JENKINS_USER --url \$JENKINS_URL --jenkins-password \$JENKINS_TOKEN --parameters PULL_NUMBER=master"